/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#cbdbf5',
        'surface-tint': '#006c4a',
        primary: '#006948',
        'on-secondary-fixed': '#111c2d',
        error: '#ba1a1a',
        'secondary-container': '#d5e0f8',
        background: '#f8f9ff',
        'secondary-fixed-dim': '#bcc7de',
        'on-secondary-fixed-variant': '#3c475a',
        'surface-container-highest': '#d3e4fe',
        'tertiary-fixed': '#e0e3e5',
        'on-background': '#0b1c30',
        'on-tertiary': '#ffffff',
        secondary: '#545f73',
        outline: '#6d7a72',
        'on-tertiary-container': '#fbfdff',
        'inverse-surface': '#213145',
        tertiary: '#595c5e',
        'secondary-fixed': '#d8e3fb',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#002114',
        'on-error': '#ffffff',
        'primary-fixed': '#85f8c4',
        'inverse-primary': '#68dba9',
        'on-primary-container': '#f5fff7',
        'surface-variant': '#d3e4fe',
        'tertiary-container': '#727577',
        'error-container': '#ffdad6',
        'on-surface': '#0b1c30',
        'primary-fixed-dim': '#68dba9',
        surface: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container': '#e5eeff',
        'surface-container-low': '#eff4ff',
        'outline-variant': '#bccac0',
        'on-secondary-container': '#586377',
        'on-primary': '#ffffff',
        'surface-bright': '#f8f9ff',
        'on-error-container': '#93000a',
        'surface-container-high': '#dce9ff',
        'on-primary-fixed-variant': '#005137',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-tertiary-fixed-variant': '#444749',
        'primary-container': '#00855d',
        'inverse-on-surface': '#eaf1ff',
        'on-surface-variant': '#3d4a42',
        'on-tertiary-fixed': '#191c1e',
        'brand-slate': '#1e293b',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        'container-margin': '24px',
        gutter: '16px',
      },
      fontFamily: {
        sans: ['HankenGrotesk_400Regular', 'System'],
        'headline-md': ['HankenGrotesk_600SemiBold', 'System'],
        'vitals-display': ['System'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'vitals-display': ['64px', { lineHeight: '64px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
